"""add finding verification models

Revision ID: 134a44ede537
Revises: 7ca50f301746
Create Date: 2026-08-25 03:03:09.635415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134a44ede537'
down_revision: Union[str, Sequence[str], None] = '7ca50f301746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('required_roles', sa.JSON(), nullable=False),
    sa.Column('required_capabilities', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum'), nullable=False),
    sa.Column('destructive', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['test_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_strategy_id'), 'test_cases', ['strategy_id'], unique=False)
    op.create_table('business_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('rule_source', sa.Enum('USER_DEFINED', 'APPLICATION_INFERRED', 'SYSTEM_GENERATED', name='rule_source_enum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rules_project_id'), 'business_rules', ['project_id'], unique=False)
    op.create_table('business_rule_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['business_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rule_versions_rule_id'), 'business_rule_versions', ['rule_id'], unique=False)
    op.create_table('application_models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('test_run_id', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('exploration_version', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('browser_version', sa.String(), nullable=False),
    sa.Column('model_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_models_project_id'), 'application_models', ['project_id'], unique=False)
    op.create_index(op.f('ix_application_models_target_id'), 'application_models', ['target_id'], unique=False)
    op.create_index(op.f('ix_application_models_test_run_id'), 'application_models', ['test_run_id'], unique=False)
    op.create_table('test_hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_attempt_id', sa.String(), nullable=False),
    sa.Column('test_case_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_attempt_id'], ['execution_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_hypotheses_execution_attempt_id'), 'test_hypotheses', ['execution_attempt_id'], unique=False)
    op.create_index(op.f('ix_test_hypotheses_test_case_id'), 'test_hypotheses', ['test_case_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('test_run_id', sa.String(), nullable=False),
    sa.Column('test_hypothesis_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('CANDIDATE', 'VERIFYING', 'CONFIRMED', 'REJECTED', 'INCONCLUSIVE', 'EXPIRED', 'RESOLVED', name='finding_status_enum'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity_level_enum'), nullable=False),
    sa.Column('confidence', sa.Enum('CONFIRMED', 'STRONG', 'WEAK', 'INCONCLUSIVE', 'FALSE_POSITIVE', name='confidence_score_enum'), nullable=False),
    sa.Column('severity_policy_version', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_hypothesis_id'], ['test_hypotheses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_project_id'), 'findings', ['project_id'], unique=False)
    op.create_index(op.f('ix_findings_target_id'), 'findings', ['target_id'], unique=False)
    op.create_index(op.f('ix_findings_test_hypothesis_id'), 'findings', ['test_hypothesis_id'], unique=False)
    op.create_index(op.f('ix_findings_test_run_id'), 'findings', ['test_run_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_attempt_id', sa.String(), nullable=False),
    sa.Column('test_hypothesis_id', sa.String(), nullable=True),
    sa.Column('expected_behavior', sa.String(), nullable=False),
    sa.Column('observed_behavior', sa.String(), nullable=False),
    sa.Column('rule_or_state_tested', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('strategy_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_attempt_id'], ['execution_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_hypothesis_id'], ['test_hypotheses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_execution_attempt_id'), 'test_results', ['execution_attempt_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_hypothesis_id'), 'test_results', ['test_hypothesis_id'], unique=False)
    op.create_table('verification_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('execution_attempt_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_attempt_id'], ['execution_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_attempts_execution_attempt_id'), 'verification_attempts', ['execution_attempt_id'], unique=False)
    op.create_index(op.f('ix_verification_attempts_finding_id'), 'verification_attempts', ['finding_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('verification_attempt_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Enum('CONFIRMED', 'STRONG', 'WEAK', 'INCONCLUSIVE', 'FALSE_POSITIVE', name='confidence_score_enum'), nullable=False),
    sa.Column('is_reproducible', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_attempt_id'], ['verification_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_verification_attempt_id'), 'verification_results', ['verification_attempt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_results_verification_attempt_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_verification_attempts_finding_id'), table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_execution_attempt_id'), table_name='verification_attempts')
    op.drop_table('verification_attempts')
    op.drop_index(op.f('ix_test_results_test_hypothesis_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_execution_attempt_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_findings_test_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_test_hypothesis_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_target_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_project_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_test_hypotheses_test_case_id'), table_name='test_hypotheses')
    op.drop_index(op.f('ix_test_hypotheses_execution_attempt_id'), table_name='test_hypotheses')
    op.drop_table('test_hypotheses')
    op.drop_index(op.f('ix_application_models_test_run_id'), table_name='application_models')
    op.drop_index(op.f('ix_application_models_target_id'), table_name='application_models')
    op.drop_index(op.f('ix_application_models_project_id'), table_name='application_models')
    op.drop_table('application_models')
    op.drop_index(op.f('ix_business_rule_versions_rule_id'), table_name='business_rule_versions')
    op.drop_table('business_rule_versions')
    op.drop_index(op.f('ix_business_rules_project_id'), table_name='business_rules')
    op.drop_table('business_rules')
    op.drop_index(op.f('ix_test_cases_strategy_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_table('test_strategies')
    # ### end Alembic commands ###
