"""Add Credential model

Revision ID: 137a877e5f30
Revises: 29e499e28420
Create Date: 2026-08-25 00:20:57.064680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137a877e5f30'
down_revision: Union[str, Sequence[str], None] = '29e499e28420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('role_label', sa.String(), nullable=False),
    sa.Column('identity_type', sa.String(), nullable=False),
    sa.Column('secret_reference', sa.String(), nullable=False),
    sa.Column('login_strategy', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_project_id'), 'credentials', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_project_id'), table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###
