"""Add target model

Revision ID: 29e499e28420
Revises: 1b342d965f7f
Create Date: 2026-08-24 23:45:45.907480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e499e28420'
down_revision: Union[str, Sequence[str], None] = '1b342d965f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('environment', sa.Enum('DEVELOPMENT', 'STAGING', 'PREVIEW', name='environment_enum'), nullable=False),
    sa.Column('allowed_hosts', sa.JSON(), nullable=False),
    sa.Column('allowed_url_prefixes', sa.JSON(), nullable=False),
    sa.Column('allowed_ports', sa.JSON(), nullable=False),
    sa.Column('authorization_status', sa.Enum('PENDING', 'AUTHORIZED', 'REJECTED', name='authorization_status_enum'), nullable=False),
    sa.Column('authorization_method', sa.String(), nullable=True),
    sa.Column('authorization_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_project_id'), 'targets', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targets_project_id'), table_name='targets')
    op.drop_table('targets')
    # ### end Alembic commands ###
