"""phase 8 finding reporting and evidence

Revision ID: 3ad39105445f
Revises: 134a44ede537
Create Date: 2026-08-25 03:12:18.284802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad39105445f'
down_revision: Union[str, Sequence[str], None] = '134a44ede537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expected_behaviors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('behavior_description', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_behaviors_project_id'), 'expected_behaviors', ['project_id'], unique=False)
    op.create_index(op.f('ix_expected_behaviors_target_id'), 'expected_behaviors', ['target_id'], unique=False)
    op.create_table('finding_fingerprints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('authorization_boundary', sa.String(), nullable=True),
    sa.Column('root_cause_category', sa.String(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_fingerprints_fingerprint_hash'), 'finding_fingerprints', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_finding_fingerprints_target_id'), 'finding_fingerprints', ['target_id'], unique=False)
    op.create_table('suppression_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_rules_project_id'), 'suppression_rules', ['project_id'], unique=False)
    op.create_index(op.f('ix_suppression_rules_target_id'), 'suppression_rules', ['target_id'], unique=False)
    op.add_column('findings', sa.Column('fingerprint_id', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('title', sa.String(), nullable=False))
    op.add_column('findings', sa.Column('affected_identity', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('expected_behavior', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('observed_behavior', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('violated_rule', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('impact', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('reproduction_steps', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('findings', sa.Column('first_detected', sa.DateTime(timezone=True), nullable=False))
    op.add_column('findings', sa.Column('last_verified', sa.DateTime(timezone=True), nullable=False))
    op.add_column('findings', sa.Column('test_strategy', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('strategy_version', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('recommended_remediation', sa.String(), nullable=True))
    op.execute("CREATE TYPE retest_status_enum AS ENUM ('resolved', 'still_vulnerable', 'unable_to_establish_equivalence')")
    op.add_column('findings', sa.Column('retest_status', sa.Enum('resolved', 'still_vulnerable', 'unable_to_establish_equivalence', name='retest_status_enum'), nullable=True))
    op.create_index(op.f('ix_findings_fingerprint_id'), 'findings', ['fingerprint_id'], unique=False)
    op.create_foreign_key(None, 'findings', 'finding_fingerprints', ['fingerprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'findings', type_='foreignkey')  # type: ignore[arg-type]
    op.drop_index(op.f('ix_findings_fingerprint_id'), table_name='findings')
    op.drop_column('findings', 'retest_status')
    op.execute("DROP TYPE retest_status_enum")
    op.drop_column('findings', 'recommended_remediation')
    op.drop_column('findings', 'strategy_version')
    op.drop_column('findings', 'test_strategy')
    op.drop_column('findings', 'last_verified')
    op.drop_column('findings', 'first_detected')
    op.drop_column('findings', 'evidence')
    op.drop_column('findings', 'reproduction_steps')
    op.drop_column('findings', 'impact')
    op.drop_column('findings', 'violated_rule')
    op.drop_column('findings', 'observed_behavior')
    op.drop_column('findings', 'expected_behavior')
    op.drop_column('findings', 'affected_identity')
    op.drop_column('findings', 'title')
    op.drop_column('findings', 'fingerprint_id')
    op.drop_index(op.f('ix_suppression_rules_target_id'), table_name='suppression_rules')
    op.drop_index(op.f('ix_suppression_rules_project_id'), table_name='suppression_rules')
    op.drop_table('suppression_rules')
    op.drop_index(op.f('ix_finding_fingerprints_target_id'), table_name='finding_fingerprints')
    op.drop_index(op.f('ix_finding_fingerprints_fingerprint_hash'), table_name='finding_fingerprints')
    op.drop_table('finding_fingerprints')
    op.drop_index(op.f('ix_expected_behaviors_target_id'), table_name='expected_behaviors')
    op.drop_index(op.f('ix_expected_behaviors_project_id'), table_name='expected_behaviors')
    op.drop_table('expected_behaviors')
    # ### end Alembic commands ###
