"""Add execution plane models

Revision ID: 7ca50f301746
Revises: 137a877e5f30
Create Date: 2026-08-25 00:41:48.671293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca50f301746'
down_revision: Union[str, Sequence[str], None] = '137a877e5f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT', 'POLICY_BLOCKED', name='test_run_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_project_id'), 'test_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_runs_target_id'), 'test_runs', ['target_id'], unique=False)
    op.create_table('execution_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_run_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='execution_job_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_jobs_test_run_id'), 'execution_jobs', ['test_run_id'], unique=False)
    op.create_table('execution_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_job_id', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='execution_attempt_status_enum'), nullable=False),
    sa.Column('log_uri', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_job_id'], ['execution_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_attempts_execution_job_id'), 'execution_attempts', ['execution_job_id'], unique=False)
    op.create_table('sandboxes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('execution_attempt_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_sandbox_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PROVISIONING', 'RUNNING', 'DESTROYED', 'FAILED', name='sandbox_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_attempt_id'], ['execution_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandboxes_execution_attempt_id'), 'sandboxes', ['execution_attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sandboxes_execution_attempt_id'), table_name='sandboxes')
    op.drop_table('sandboxes')
    op.drop_index(op.f('ix_execution_attempts_execution_job_id'), table_name='execution_attempts')
    op.drop_table('execution_attempts')
    op.drop_index(op.f('ix_execution_jobs_test_run_id'), table_name='execution_jobs')
    op.drop_table('execution_jobs')
    op.drop_index(op.f('ix_test_runs_target_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_project_id'), table_name='test_runs')
    op.drop_table('test_runs')
    # ### end Alembic commands ###
